---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nzbget.fullname" . }}-config
  labels:
    {{- include "nzbget.labels" . | nindent 4 }}
stringData:
  nzbget.conf: |
  {{- range $key, $val := .Values.nzbget.config }}
    {{ $key }}={{ $val }}
  {{- end }}

