---
# name is the name of this release and the base for all helm-managed resources
name: nzbget

# ingress block is used to define an Ingress for the service
ingress:
  # enabled determines whether the Ingress is generated
  enabled: false
  # hostname is used both for the virtual host and for SNI in the TLS cert
  hostname: nzbget
  # annotations are applied to the Ingress, e.g., `cert-manager.io/cluster-issuer`
  annotations:
