{{- with .Values.ingress -}}
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "radarr.fullname" $ }}
  labels:
    {{- include "radarr.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
  - hosts:
    - {{ .host | quote }}
    secretName: {{ .secretName | default ( printf "%s-%s" ( include "radarr.fullname" $ ) "tls" ) }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "radarr.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
{{- end }}
